spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: Mysql@143
   
  jpa:
    hibernate:
      ddl-auto: update
    properties: 
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
              
server:
  port: 9090  
  
